language: node_js
node_js: 'lts/*'
cache: npm
jobs:
  include:
    - stage: lint
      if: branch = dev OR branch = master
      name: 'Lint: Prettier'
      script: './node_modules/prettier/bin-prettier.js --check src/**/*'
    - stage: build
      script: npm run build
    - stage: test
      script: npm run test
    - stage: deploy
      script: 'firebase deploy --only hosting --token $FIREBASE_DEPLOY_KEY -m "$TRAVIS_COMMIT: $TRAVIS_COMMIT_MESSAGE"'
