language: node_js
node_js: 'lts/*'
cache: npm
before_install:
  - npm install -g firebase-tools
jobs:
  include:
    - stage: lint
      if: branch = dev OR branch = master
      name: 'Lint: Prettier'
      script: './node_modules/prettier/bin-prettier.js --check src/**/*'
    - stage: build
      if: branch = dev OR branch = master
      script: npm run build
    - stage: test
      if: branch = dev OR branch = master
      script: npm run test
    - stage: deploy
      if: branch = master
      script: npm run build
      script: 'firebase deploy --only hosting --token $FIREBASE_DEPLOY_KEY -m "${TRAVIS_COMMIT}: ${TRAVIS_COMMIT_MESSAGE}"'
