language: node_js
jobs:
  include:
    - stage: "lint_test_build"
      if: branch = dev OR branch = master
      name: "Lint: Prettier"
      script: ./node_modules/prettier/bin-prettier.js 
      name: "Build: App"
      script: npm build 
      name: "Test"
      script: npm test
    - stage: "deploy"
      if: branch = master
      script: "echo 'deploy here'"
  
